{
 "title": "Pingbot",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Host", "query": { "query": "hostname" } }
  ]
 },
 "panels": [
  {
   "title": "Non-Production Total Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pingbot_total_success_total{production=\"False\"}"
    }
   ]
  },
  {
   "title": "Production Total Successes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pingbot_total_success_total{production=\"True\"}"
    }
   ]
  },
  {
   "title": "Pingbot Non-Production hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "pingbot_ping{production=\"False\",job=\"pingbot\"}"
    }
   ]
  },
  {
   "title": "Pingbot Production hosts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "pingbot_ping{production=\"True\"}"
    }
   ]
  }
 ]
}